### ISSUE TITLE
Add include and exclude options

### ISSUE THREAD

**Issue by marianobianchi** [jeanbmar/s3-sync-client#11]
Is there a way of adding --include and --exclude options in the current implementation to mimic the same options from AWS CLI sync functionality?

**Comment by jeanbmar** [comment]
It's not possible at the moment, but I've been thinking about this for some time.
I'm trying to assess what would be the best solution considering we aren't doing pure CLI but Node.js.

## Option 1
Implement original `include` and `exclude` options and use [minimatch](https://github.com/isaacs/minimatch) to perform filter evaluation.

Pros:
- Easier to migrate from the original CLI to s3-sync-client

Cons:
- Minimatch would have to be bundled as a dependency to s3-sync-client to cover what I assume to be an edge case
- Minimatch syntax isn't exactly the same as CLI syntax

## Option 2
Implement a `filter` option in the spirit of [Array.prototype.filter](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/filter).

Pros:
- Very flexible
- No additional dependency to the project

Cons:
- Migration from CLI can't be done seamlessly

**Comment by jeanbmar** [comment]
## Option 3
```js
// sync options
{
  filters: [
    { exclude: (key) => /* user logic */ },
    { include: (key) => /* user logic */ },
    { exclude: (key) => /* more user logic */ },
  ]
}
```

In this scenario, filters entries return a boolean. The user is responsible for implementing the filtering logic (could be String.prototype.includes for simple cases, regular expressions, minimatch, etc.)

Pros:
- Very flexible
- No additional dependency to the project
- Sticking to AWS sync logic

Cons:
- None

**Comment by jeanbmar** [comment]
Closed by https://github.com/jeanbmar/s3-sync-client/pull/21.
