### ISSUE TITLE
Add automatic mime type for uploaded files

### ISSUE THREAD

**Issue by coyotte508** [jeanbmar/s3-sync-client#13]
First of all, thank you very much. 

I'm using another S3 provider than Amazon (Scaleway) and no matter what I did (even with `--endpoint-url`), in Github Actions, the domain would always be replaced by amazon's. Mind-boggling.

[Using](https://github.com/coyotte508/coyo/commit/6a7bcd2927d13d3de575766c37077eeae6f6fa0e) your npm module in lieu of the aws cli saved my hide ^^

Regarding the issue - files do not seem to be uploaded with the corresponding mime-type. When downloading the file from the S3 storage, I get "application/octet-stream" in the "Content-Type" header. Which is annoying when proxying to S3 to make a website 😄  (I ended up configuring nginx to remove the header)

**Comment by jeanbmar** [comment]
Thank you, I'm glad the module is useful to you.

You should be able to set the mime type dynamically using the commandInput option:

```js
const mime = require('mime-types');
const S3SyncClient = require('s3-sync-client');

const client = new S3SyncClient({ /* credentials */ });

await client.sync('dist', 's3://coyo.dev', {
    del: true,
    commandInput: {
        ContentType: (syncCommandInput) => (
            mime.lookup(syncCommandInput.Key) || 'text/html'
        ),
    },
});
```
