### ISSUE TITLE
downloads bucket prefix as directory inside target

### ISSUE THREAD

**Issue by atomantic** [jeanbmar/s3-sync-client#15]
I want to sync s3://bucket-name/path-prefix/ to a local folder path like /some/path, but it's downloading the sync into /some/path/path-prefix/* rather than syncing all the files with the path prefix into the target directory.

**Comment by jeanbmar** [comment]
Hey there, you will need to use relocation for this.
You can see some examples here: https://github.com/jeanbmar/s3-sync-client#relocate-objects-during-sync

**Comment by atomantic** [comment]
Ah! perfect. Thanks!
