### ISSUE TITLE
Consider migration to typescript, folder watch, and progress notifications?

### ISSUE THREAD

**Issue by J-Rojas** [jeanbmar/s3-sync-client#2]
Hi, I'm looking for a simple sync library like this. I'll need to modify it to support watching a folder and uploading only the modified files. 

Also I would like to have progress notifications passed through but maybe that's easily done by exposing the underlying s3 client.

I'm also wondering, would you consider adopting typescript for any PR contributions?

**Comment by jeanbmar** [comment]
Hi,
I think the watch logic is complementary to the sync logic, but that it should be kept aside to keep things simple.  
I would rather use something like chokidar to do:

```javascript
chokidar.watch('.').on('all', () => sync.bucketWithLocal(/* ... */));
```

Calling bucketWithLocal will upload only new / modified files with the current implementation: 
https://github.com/jeanbmar/s3-sync-client/blob/f3887c8b93cdfe7008973186c3714a0c8d05e04b/lib/util.js#L19-L25

Progress would be a nice addition and I plan to implement it next week. I'm thinking about something like passing an optional event emitter instance to the sync call:
```javascript
// same logic would be applicable to downloads
const uploadManager = new EventEmitter();
uploadManager.on('progress', ({ loaded, total }) => console.log(`uploaded ${loaded} of ${total}`));
setTimeout(() => uploadManager.emit('abort'), 50000); // transfers can be aborted, sync promise is rejected
await bucketWithLocal(localDir, bucketPrefix, { uploadManager });
```

I would see TS as a nice addition too, PR welcomed 👍.

**Comment by jeanbmar** [comment]
Progress tracking implemented in https://github.com/jeanbmar/s3-sync-client/commit/1b4acaba1621521ee3da6c55cffd3c4b2318a198.
Examples: https://github.com/jeanbmar/s3-sync-client#track-transfer-progress
