### ISSUE TITLE
Convert the module to TypeScript

### ISSUE THREAD

**Issue by jeanbmar** [jeanbmar/s3-sync-client#28]

**Comment by xiaoxiangmoe** [comment]
@jeanbmar I can help you to do this. Should I create a PR for this?

**Comment by jeanbmar** [comment]
Sure go ahead! I've started a branch for the conversion at the beginning of the month (https://github.com/jeanbmar/s3-sync-client/tree/ts/src/sync-managers). Feel free to use it or to start from master, as you prefer. Thanks!

**Comment by welcomemax** [comment]
Hello! Is there any progress or timeline with TS? I can also lend a helping hand.
