### ISSUE TITLE
Support AWS CLI option --acl

### ISSUE THREAD

**Issue by dsietziapp** [jeanbmar/s3-sync-client#32]
When syncing objects to the S3 bucket, it is often necessary to also set the [ACL](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/sync.html#options) at the same time. 

```
--acl bucket-owner-full-control --recursive
```

This can be done using the [SDK PutObjectAclCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/putobjectaclcommand.html), however, it would be so much easier if it were one of the supported options.

**Comment by jeanbmar** [comment]
Hey there, it is already implemented through the commandInput option (https://github.com/jeanbmar/s3-sync-client#use-aws-sdk-command-input-options):

```js
// set ACL, fixed value
await sync('s3://mybucket', '/path/to/local/dir', {
    commandInput: {
        ACL: 'aws-exec-read',
    },
});
```

**Comment by dsietziapp** [comment]
That's fantastic. Thanks for the fast reply!
