### ISSUE TITLE
Is it possible to sync between 2 different regions?

### ISSUE THREAD

**Issue by ouwyukha** [jeanbmar/s3-sync-client#34]
Hello, i wonder if this module is capable to sync between 2 different regions or maybe 2 different private S3?

I need something like this
```
clientA = S3;
clientB = S3;

client = syncClient(clientA, clientB);
client.sync(bucketA, bucketB);
````

Thank you in advance

**Comment by jeanbmar** [comment]
Hello, yes it is possible and I see 2 options.

This lib uses [CopyObjectCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/copyobjectcommand.html) under the hood when synchronizing 2 buckets.
The AWS way is to configure the 2 buckets so account 1 can read from (or write to) account 2 bucket.
You will use a single client for this operation.

The other option if you don't want to deal with bucket config is to copy locally with account 1 and to transfer to remote bucket with account 2. Of course it means extra io and bandwidth consumption.
```js
clientA.sync(bucketA, './local');
clientB.sync('./local', bucketB);
```

**Comment by ouwyukha** [comment]
Thanks! This is exactly what i need
