### ISSUE TITLE
Last modified date not set to S3 date when synced from bucket to local

### ISSUE THREAD

**Issue by gtownfunk** [jeanbmar/s3-sync-client#36]
When syncing from an S3 bucket to local, it makes sense that the last modified date on the file should be set to what it is on S3.  This way immediately syncing back from local->S3 will not upload all the files again (because the date was just set to the current date and is newer than the last modified date on S3).

I'm able to use the sizeOnly option for a temporary workaround, but that is not ideal for obvious reasons.

Thank you, love the project!

**Comment by jeanbmar** [comment]
Hey there!
I agree. I have to verify how AWS cli behaves in this situation and I will fix accordingly.

**Comment by jeanbmar** [comment]
Closed by https://github.com/jeanbmar/s3-sync-client/pull/37.

Thank you for documenting the issue!  👍
