### ISSUE TITLE
Sync local with remote S3 behaves different from AWS CLI.

### ISSUE THREAD

**Issue by DiscreteTom** [jeanbmar/s3-sync-client#40]
For example, I want to sync local `C:/Users/xxx/Musics` from `s3://bucket/aaa/bbb/Musics`.

Expected behavior: `s3://bucket/aaa/bbb/Musics/123.mp3` => `C:/Users/xxx/Musics/123.mp3`.

Actual behavior: `s3://bucket/aaa/bbb/Musics/123.mp3` => `C:/Users/xxx/Musics/aaa/bbb/Musics/123.mp3`.

To avoid this, I have to use `relocations: [['aaa/bbb', '']]`.

**Comment by DiscreteTom** [comment]
Besides, since relocations are applied after filters, for filters the object key is `aaa/bbb/Musics/123.mp3` instead of `123.mp3`, which may cause more complex filter.

**Comment by jeanbmar** [comment]
Hello @DiscreteTom,

How do you flatten `aaa/bbb/Musics/123.mp3` to `Musics/123.mp3` with AWS CLI sync?
It's impossible as far as I know, so I don't understand the title of the issue.

About relocations vs filters order, indeed filters have to be applied first. Doing differently could break implementations of people transitioning from AWS CLI sync and would add potential conflicts.
It doesn't really make filters more complex. If you were relocating from `x.mp3` to `a/b/c/x.mp3`, filters would be shorter. It just depends on your use case.

**Comment by jeanbmar** [comment]
I'm closing, feel free to reopen if you want to discuss this further.

**Comment by DiscreteTom** [comment]
Sorry for the late response.

I'm using AWS CLI V2.

E.g. if I run `aws s3 sync s3://bucket/aaa/bbb/Music C:/Users/xxx/Music`, then `s3://bucket/aaa/bbb/Music/123.mp3` will be downloaded into `C:/Users/xxx/Music/123.mp3`.

But if I use this lib, run `sync('s3://bucket/aaa/bbb/Music', 'C:/Users/xxx/Music')`, then the file will be downloaded into `C:/Users/xxx/Music/aaa/bbb/Music/123.mp3`.

**Comment by jeanbmar** [comment]
Finally found the time to fix it. Thanks for the clean repro case!
