### ISSUE TITLE
Is there any way to know if a file is changed its content by sync?

### ISSUE THREAD

**Issue by bugb** [jeanbmar/s3-sync-client#42]
Just want to know if your library can support a case like this:

If files are updated its content on S3 then your lib can return something like this: Files are updated/sync
 
Else something like this: No updated files from S3, skip sync

**Comment by jeanbmar** [comment]
Hello there,

Yes, sort of.
The doc isn't great for this feature, it will be better when I finish the TypeScript migration. Sorry!

Before running a sync, the module performs a diff between the source and the destination.
The `sync` method returns the diff object within a Promise.

```js
// aws s3 sync s3://mybucket2 /path/to/local/dir
const syncOps = await sync('s3://mybucket2', '/path/to/local/dir');
console.log(syncOps); // this is the diff
```

You can use the `dryRun` option if you need to retrieve the diff before syncing.
The diff object contains created, updated and deleted entries. 
It doesn't contain unmodified entries, at least for now. But a PR is welcome if you want to give it a try 😊 (change should probably happen [here](https://github.com/jeanbmar/s3-sync-client/blob/master/lib/utilities/sync-diff.js).
