### ISSUE TITLE
Sync operation doesn't finish

### ISSUE THREAD

**Issue by jeanbmar** [jeanbmar/s3-sync-client#43]
Hi @jeanbmar 
I'm seeing a very similar issue.
I'm syncing from local (EFS) to S3, and sometimes I have a timeout (in lambda after 15 minutes).
I added a monitor to see what's happening, but during all the 15 minutes I'm only seeing this:
![image](https://user-images.githubusercontent.com/1325474/203377953-20f584fa-128c-4548-9fa1-700f3d5c89de.png)

It looks like nothing has to be synced, but the `sync` method doesn't end.
Any idea?

_Originally posted by @ChristopheBougere in https://github.com/jeanbmar/s3-sync-client/issues/33#issuecomment-1323998077_

**Comment by ChristopheBougere** [comment]
I just figured out that in the snippet from https://github.com/jeanbmar/s3-sync-client/issues/33#issuecomment-1324073744, I wasn't passing the `monitor` instance as an option of the `sync` method. This might explain the fact we don't see anything in the logs above.
I'll continue investigating with the monitor working

**Comment by jeanbmar** [comment]
I'm converting the module to TS, and I've identified a possible race condition that could lead to an issue like yours in https://github.com/jeanbmar/s3-sync-client/blob/67c9758611ae8d187649ac3abcde6afe15754e52/lib/sync-objects/local-object.js#L20
Stream finishing too early could potentially prevent the promise from resolving. It will be fixed soon.
