### ISSUE TITLE
Sync not following symlinks

### ISSUE THREAD

**Issue by agouil** [jeanbmar/s3-sync-client#51]
I'm trying to sync a directory with subdirectories to an S3 bucket which may contain broken symlinks. At the moment, the lib is following the symlinks which will result in an ENOENT error if one is broken.

Is there any way to not follow symlinks at the moment?  
Are any plans to support these options from the AWS CLI `--follow-symlinks`,  `--no-follow-symlinks` ?

**Comment by jeanbmar** [comment]
Hello there,

Untested example but I would go with something like:

```js

await sync('my/local/path', 's3://my-bucket', {
  filters: [
    { exclude: (path) => fs.lstatSync(path).isSymbolicLink() }
  ]
})
```

You might implement additional logic to exclude only invalid symlinks.

We could support the options natively if more people request it or if someone opens a PR for it!
