### ISSUE TITLE
The order of the arguments in the usage example in the docs is wrong

### ISSUE THREAD

**Issue by arsinclair** [jeanbmar/s3-sync-client#54]
There's a mistake in the README documentation. Here (https://github.com/jeanbmar/s3-sync-client#sync-the-local-file-system-with-a-remote-s3-bucket) it says:

> Sync the local file system with a remote S3 bucket
> `await sync('s3://mybucket', '/path/to/some/local', { del: true });`

However it should be the other way around, since the first argument is the source and the second is target. The heading states that it should sync a local folder into the remote S3 bucket, but it's doing exactly the opposite.

This can lead to a data loss locally, in fact, I didn't verify that this method is working as document, so a bunch of local files got deleted. Fortunately, I was testing it on a random directory and not something important.

**Comment by jeanbmar** [comment]
It is not really a mistake since it's intended to mean "synchronize a `target` *with* a `source`".

But I understand it can be misleading. I'll change it to `Sync from S3 bucket to local file system`.

**Comment by arsinclair** [comment]
Thanks for making it more clear!
