### ISSUE TITLE
Can we have different log for sync?

### ISSUE THREAD

**Issue by multivoltage** [jeanbmar/s3-sync-client#56]
I come from a cli usage where I logged all info with:

```js
import { exec } from "child_process";
const commandProcessSync = exec("aws sync bla ba bla");
const { stdout, stderr } = commandProcessSync;
if (stdout) {
  stdout.on("data", function (data) {
    console.log(data);
  });
}
if (stderr) {
  stderr.on("data", function (data) {
    console.error(data);
  });
}
```

and I can log like;
```js
Completed 272.7 MiB/273.2 MiB (6.5 MiB/s) with 1 file(s) remaining
Completed 273.0 MiB/273.2 MiB (6.5 MiB/s) with 1 file(s) remaining
Completed 273.2 MiB/273.2 MiB (6.5 MiB/s) with 1 file(s) remaining
download: s3://mybucket.com/video/vvideo.mp4.webm to bucket/mybucket.com/video/vvideo.webm
```

can we do that? Or maybe I can develop with PR?

**Comment by jeanbmar** [comment]
Hello,

There's no logger at the moment, but we can monitor transfers using the [TransferMonitor](https://github.com/jeanbmar/s3-sync-client/blob/master/src/TransferMonitor.ts).

There is certainly room for improvement on this part, feel free to share your ideas and submit a PR :).

**Comment by multivoltage** [comment]
Yes monitor is ok. 
I have 2 goals:
- comunicate to user that somerthigns is happening (monitor do great job)
- comunicate some details like my previous comment (maybe I will open PR)

thanks.

I will use this Issue for some suggestion about PR.
