### ISSUE TITLE
Relocations with delete option doesn't work as expected

### ISSUE THREAD

**Issue by momo-com** [jeanbmar/s3-sync-client#9]
The following instruction should flatten the folder, sync and delete objects that are not existing anymore in the bucket:

sync.localWithBucket('my_bucket/images/ducks', '/mnt/images/', { relocations: [['images/ducks', '']], del: true });

The actual result is that it deletes everything in the destination folder.

**Comment by jeanbmar** [comment]
Just noticed [diff](https://github.com/jeanbmar/s3-sync-client/blob/master/lib/util.js#L15) doesn't use relocated object ids properly.
I will push a fix today.
Good catch thank you!

**Comment by jeanbmar** [comment]
Fixed in [1.5.1](https://www.npmjs.com/package/s3-sync-client) https://github.com/jeanbmar/s3-sync-client/commit/566e952d7a6fc72b8b80e629c4ed8289f210cbb0
